# Generated by Django 3.1.5 on 2023-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doneez_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_website',
            field=models.URLField(help_text='Enter your business web address.  If you have a referral link, please supply it here, instead of your web address.', max_length=100, verbose_name='Website Address or Referral Link'),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='b2b',
            field=models.CharField(choices=[('RETAIL', 'This business serves Retail Customers'), ('SUPPLIER', 'This business supplies other businesses with parts and supplies'), ('SERVICE', 'This business offers affiliate products and services to other businesses')], default='RETAIL', help_text='Indicates whether this is a B2B business, where its products and services are offered to other businesses only.  If selected, the business will only appear in B2B searches.', max_length=10, verbose_name='B2B'),
        ),
    ]
