# Generated by Django 3.1.5 on 2022-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doneez_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_tagline',
            field=models.TextField(blank=True, help_text="Provide a concise tagline to appear in customer's search results.", max_length=70, verbose_name='Business Tagline'),
        ),
    ]
