# Generated by Django 3.1.5 on 2023-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doneez_app', '0003_auto_20230514_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_address_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=20, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_address_map_status',
            field=models.CharField(blank=True, choices=[('Map Unverified', 'Map Unverified'), ('Map Verified', 'Map Verified'), ('Map Error', 'Map Error.')], default='Map Unverified', max_length=14, verbose_name='Map Status'),
        ),
    ]
