# Generated by Django 3.1.5 on 2023-06-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doneez_app', '0004_auto_20230627_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_address_map_status',
            field=models.CharField(blank=True, choices=[('Map Unverified', 'Map Unverified'), ('Map Verified', 'Map Verified'), ('Map Error', 'Map Error')], default='Map Unverified', max_length=14, verbose_name='Map Status'),
        ),
    ]
